### ISSUE TITLE
Requirements, server and performance

### ISSUE THREAD

**Issue by karelin** [aws-samples/aws-cdk-deep-learning-image-vector-embeddings-at-scale-using-aws-batch#1]
Thank you for great example!

Could you give some clues on a few missing questions:
1) How the requirements for processing code are defined? 
The `requirements.txt` in the project root only lists CDK libraries.
2) What virtual server have you tested the demo and which performance (say, images per second) did you achieved?
We're working on the similar project and wanted to check what resources to use.

**Comment by fsaina** [comment]
Thank you for having a look at the code example!

Regarding your questions:

1. As you mentioned, the `requirements.txt` file contains CDK related libraries to deploy the necessary AWS cloud infrastructure for the exercise. The libraries for the processing/runtime code are located in the  `src_batch_job/environment.yaml` file. That file is used by [conda](https://docs.conda.io/projects/conda/en/latest/index.html) to define a conda environment and install python dependencies. If you would like to add libraries trough pip in the conda environment file, you can take a look at the conda documentation about [using pip in an environment](https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#using-pip-in-an-environment) and an [example](https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#creating-an-environment-file-manually) conda environment file which lists pip libraries. Alternatively, you can create a  `requirements.txt` file in `src_batch_job` directory and install dependencies by modifying `src_batch_job/Dockerfile` and invoking the `pip install -r requirements.txt` command at docker image build-time.
2. Since performance might vary greatly depending on the individual use-case and implementation details (e.g. sizes of individual images being processed, execution time-limit, the computational complexity and memory footprint of the model being used, the chosen instance types, etc.) an in-depth performance analysis was outside of scope for this blog-post. In order to reduce costs of readers going trough this exercise, the current code is currently set to maximum 4 instances running at the same time with an 30 minutes instance execution time limit. You can change those limits in the CDK stack code (e.g. [max_vcpus](https://github.com/aws-samples/aws-cdk-deep-learning-image-vector-embeddings-at-scale-using-aws-batch/blob/main/batch_job_cdk/stack.py#L115) / [vcpus](https://github.com/aws-samples/aws-cdk-deep-learning-image-vector-embeddings-at-scale-using-aws-batch/blob/main/batch_job_cdk/stack.py#L85) = 32 / 8 = 4 instances, and instance [timeout](https://github.com/aws-samples/aws-cdk-deep-learning-image-vector-embeddings-at-scale-using-aws-batch/blob/main/batch_job_cdk/stack.py#L88) = 30 min) as a starting point to measure performance metrics you are interested in and which are relevant to your use-case.

**Comment by karelin** [comment]
Thank you a lot!
(another question goes to another issue)
